cni:
  chainingMode: "portmap"
ipam:
  mode: "kubernetes"
identityAllocationMode: "crd"
prometheus:
  enabled: true
rollOutCiliumPods: true
routing-mode: "tunnel"
tunnel-protocol: "geneve"
operator:
  prometheus:
    enabled: true
